# Generated by Django 5.0.4 on 2024-04-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Рейтинг товара'),
        ),
    ]
