# Generated by Django 5.0.4 on 2024-06-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0002_product_price_product_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(
                    upload_to='product_photos/', verbose_name='фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='product_service.product', verbose_name='продукт')),
            ],
        ),
    ]
