# Generated by Django 5.0.4 on 2024-06-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0004_product_main_photo_alter_product_owner'),
        ('user_service', '0003_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name=' главная фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.seller'),
        ),
    ]
