# Generated by Django 5.0.4 on 2024-06-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0005_alter_product_main_photo_alter_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(
                    upload_to='product_photos/', verbose_name='фотография')),
            ],
        ),
    ]
