# Generated by Django 5.0.4 on 2024-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_saller',
            field=models.BooleanField(default=False),
        ),
    ]
